### ISSUE TITLE
installing on node > 0.4 fails with npm

### ISSUE THREAD

**Issue by jwcooper** [masylum/twitter-js#4]
~/dev/apps/coobro/app$ npm install twitter-js
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: twitter-js@0.0.7
npm ERR! Required: {"node":">=0.2.0 <0.3.0"}
npm ERR! Actual:   {"npm":"1.0.6","node":"v0.4.7"}
npm ERR! 
npm ERR! System Linux 2.6.38-8-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "twitter-js"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jwcooper/dev/apps/coobro/app/npm-debug.log
npm not ok

**Comment by masylum** [comment]
Try again, works now!
My fault, the package.json was ok on the repo but not published to npm.
