### ISSUE TITLE
Accesing the data

### ISSUE THREAD

**Issue by cayasso** [masylum/twitter-js#5]
Just a really quick and dom question because I have no time to double check right now, how do I access twitter data(name, screenName, location, lang, etc) from twit response?

**Comment by masylum** [comment]
I don't understand 100% the question. Anyway, if its API related check the documentation, I don't have time neither.
http://dev.twitter.com/doc

twitter_client.apiCall(http_verb, path, params, function (error, result) {
  console.log(result);
});

You have an example in the Readme
